name: Build GraphScope Wheels on Linux

on:
  # Trigger the workflow on push or pull request, but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-12
    strategy:
      matrix:
        python-version: ['3.11']

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        brew update || true
        brew install bash coreutils

        alias bash=$(brew --prefix)/bin/bash

        export PATH=$HOME/.local/bin:$HOME/Library/Python/${{ matrix.python-version }}/bin:$PATH

        sudo mkdir /opt/graphscope
        sudo chown -R $(id -u):$(id -g) /opt/graphscope

        python3 -m pip install click

    - name: clone
      run: |
        brew update || true
        git clone https://github.com/alibaba/GraphScope.git
        cd GraphScope
        python3 -m pip install click packaging
        python3 gsctl.py install-deps dev || true
        python3 gsctl.py install-deps dev

        echo "export PATH=/usr/local/opt/coreutils/libexec/gnubin:\$PATH" >> ~/.graphscope_env
    
    - name: Reinstall glog
      run: |
        # Essential cause glog installed by brew is broken and produce corrupted messages
        brew uninstall --ignore-dependencies glog
        . ~/.graphscope_env
        git clone https://github.com/google/glog.git -b v0.6.0
        cd glog

        cmake . -DWITH_TLS=OFF -DWITH_SYMBOLIZE=OFF -DWITH_UNWIND=OFF -DWITH_GTEST=OFF -DBUILD_TESTING=OFF
        make -j
        sudo make install

        # make delocate-wheel happy
        sudo mkdir -p /usr/local/opt/glog/lib
        sudo ln -s /usr/local/lib/libglog*.dylib /usr/local/opt/glog/lib/

    - name: Prepare Build Server Wheel
      run: |
        # source environment variable
        . ~/.graphscope_env
        python3 -m pip install libclang
        # echo ${CC}
        # make sure the python's local bin is in PATH (by `pip install --user`)
        export PATH=$HOME/.local/bin:$HOME/Library/Python/${{ matrix.python-version }}/bin:$PATH
        python3 -m pip install numpy pandas "grpcio>=1.49" "grpcio-tools>=1.49" "mypy-protobuf>=3.4.0" wheel
    
    - name: Setup tmate session
      if: true
      uses: mxschmitt/action-tmate@v2
